name: container-build

on:
  push:
    branches:
      - main
  workflow_dispatch:

env:
  PODMAN_VERSION: "4.5.0"
  IMAGE: podman-dind

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE }}
          tags: |
            latest
            ${{ env.PODMAN_VERSION }}
          containerfiles: ./Containerfile
          build-args: |
            PODMAN_VERSION=${{ env.PODMAN_VERSION }}
          oci: false # healthcheck is only supported in docker format
          layers: true
          extra-args: --cache-from ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE }}

      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@v2
        id: push-ghcr
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: |
            ${{ steps.build_image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ github.token }}

  build-systemd-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Image
        id: build_image
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE }}
          tags: |
            systemd
            ${{ env.PODMAN_VERSION }}-systemd
          containerfiles: ./Containerfile.systemd
          build-args: |
            PODMAN_VERSION=${{ env.PODMAN_VERSION }}
          oci: false # healthcheck is only supported in docker format
          layers: true
          extra-args: --cache-from ghcr.io/${{ github.repository_owner }}/${{ env.IMAGE }}

      - name: Push To GHCR
        uses: redhat-actions/push-to-registry@v2
        id: push-ghcr
        with:
          image: ${{ steps.build_image.outputs.image }}
          tags: |
            ${{ steps.build_image.outputs.tags }}
          registry: ghcr.io/${{ github.repository_owner }}
          username: ${{ github.actor }}
          password: ${{ github.token }}
